### ISSUE TITLE
Fable REPL fails to load - certificate expired?

### ISSUE THREAD

**Issue by oshawa-connection** [fsharp/fsharp.org#931]
http://fable.io/repl3/
Uncaught DOMException: Failed to construct 'Worker': Script at 'https://fable.io/repl/js/repl/worker.min.js' cannot be accessed from origin 'http://fable.io'.
    at ch (http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:198447)
    at Th (http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:218043)
    at Ih (http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:218498)
    at http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:169247
    at http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:19692
    at e (http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:220396)
    at Xl.init (http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:19692)
    at tc (http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:163069)
    at http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:222894
    at http://fable.io/repl3/app.01b4c538d0046b79fd57.js:38:222907

Possibly the certificate expired?

**Comment by vzarytovskii** [comment]
Should probably be opened in the fable repo

**Comment by bbatsov** [comment]
Another ticket that can be closed. (also seems Fable have fixed this on their end)

**Comment by dsyme** [comment]
Thanks!
